name: irecipe
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.2
  flutter_bloc: ^8.1.3
  lottie: ^2.6.0
  cupertino_icons: ^1.0.2
  flavor: ^2.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.18.0


dev_dependencies:

  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # assets:
  #   - assets/lottie/
