name: irecipe
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.2
  flutter_bloc: ^8.1.3
  lottie: ^2.6.0
  cupertino_icons: ^1.0.2
  flavor: ^2.0.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.18.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_crashlytics: ^3.3.7
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  uuid: ^4.1.0
  flutter_gen: ^5.3.1
  super_toast:
    git:
      url: https://github.com/ruveydagunal/super_toast


dev_dependencies:
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.1


flutter:

  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/png/
    - assets/images/svg/
